"""Corrected mark_as_complete name

Revision ID: 526f6e92091f
Revises: 37764a040216
Create Date: 2026-08-01 19:29:15.327350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526f6e92091f'
down_revision = '37764a040216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark_as_complete', sa.Boolean(), nullable=True))
        batch_op.drop_column('marked_as_complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_as_complete', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('mark_as_complete')

    # ### end Alembic commands ###
